#!/usr/bin/env python

# Tables -----------------------------------------------------------------------
TABLE_BUSINESS = {
    1:  'Aeronautics',
    2:  'Agriculture',
    3:  'Art',
    4:  'Assassination',
    5:  'Asteroid Mining',
    6:  'Astrotech',
    7:  'Biotech',
    8:  'Bootlegging',
    9:  'Computer Hardware',
    10: 'Construction',
    11: 'Cybernetics',
    12: 'Electronics',
    13: 'Energy Weapons',
    14: 'Entertainment',
    15: 'Espionage',
    16: 'Exploration',
    17: 'Fishing',
    18: 'Fuel Refining',
    19: 'Gambling',
    20: 'Gemstones',
    21: 'Gengineering',
    22: 'Grav Vehicles',
    23: 'Heavy Weapons',
    24: 'Ideology',
    25: 'Illicit Drugs',
    26: 'Journalism',
    27: 'Law Enforcement',
    28: 'Liquor',
    29: 'Livestock',
    30: 'Maltech',
    31: 'Mercenary Work',
    32: 'Metallurgy',
    33: 'Pharmaceuticals',
    34: 'Piracy',
    35: 'Planetary Mining',
    36: 'Plastics',
    37: 'Pretech',
    38: 'Prisons',
    39: 'Programming',
    40: 'Projectile Guns',
    41: 'Prostitution',
    42: 'Psionics',
    43: 'Psitech',
    44: 'Robotics',
    45: 'Security',
    46: 'Shipyards',
    47: 'Snacks',
    48: 'Telcoms',
    49: 'Transport',
    50: 'Xenotech'
}

TABLE_NAME = {
    1:  'Ad Astra',
    2:  'Colonial',
    3:  'Compass',
    4:  'Daybreak',
    5:  'Frontier',
    6:  'Guo Yin',
    7:  'Highbeam',
    8:  'Imani',
    9:  'Magnus',
    10: 'Meteor',
    11: 'Neogen',
    12: 'New Dawn',
    13: 'Omnitech',
    14: 'Outertech',
    15: 'Overwatch',
    16: 'Panstellar',
    17: 'Shogun',
    18: 'Silverlight',
    19: 'Spiker',
    20: 'Stella',
    21: 'Striker',
    22: 'Sunbeam',
    23: 'Terra Prime',
    24: 'Wayfarer',
    25: 'West Wind'
}

TABLE_ORGANIZATION = {
    1:  'Alliance',
    2:  'Association',
    3:  'Band',
    4:  'Circle',
    5:  'Clan',
    6:  'Combine',
    7:  'Company',
    8:  'Cooperative',
    9:  'Corporation',
    10: 'Enterprises',
    11: 'Faction',
    12: 'Group',
    13: 'Megacorp',
    14: 'Multistellar',
    15: 'Organization',
    16: 'Outfit',
    17: 'Pact',
    18: 'Partnership',
    19: 'Ring',
    20: 'Society',
    21: 'Sodality',
    22: 'Syndicate',
    23: 'Union',
    24: 'Unity',
    25: 'Zaibatsu'
}

TABLE_REPUTATION = {
    1:   'Reckless with the lives of their employees',
    2:   'Reckless with the lives of their employees',
    3:   'Reckless with the lives of their employees',
    4:   'Reckless with the lives of their employees',
    5:   'Reckless with the lives of their employees',
    6:   'Have a dark secret about their board of directors',
    7:   'Have a dark secret about their board of directors',
    8:   'Have a dark secret about their board of directors',
    9:   'Have a dark secret about their board of directors',
    10:  'Have a dark secret about their board of directors',
    11:  'Notoriously xenophobic towards aliens',
    12:  'Notoriously xenophobic towards aliens',
    13:  'Notoriously xenophobic towards aliens',
    14:  'Notoriously xenophobic towards aliens',
    15:  'Notoriously xenophobic towards aliens',
    16:  'Lost much money to an embezzler who evaded arrest',
    17:  'Lost much money to an embezzler who evaded arrest',
    18:  'Lost much money to an embezzler who evaded arrest',
    19:  'Lost much money to an embezzler who evaded arrest',
    20:  'Lost much money to an embezzler who evaded arrest',
    21:  'Reliable and trustworthy goods',
    22:  'Reliable and trustworthy goods',
    23:  'Reliable and trustworthy goods',
    24:  'Reliable and trustworthy goods',
    25:  'Reliable and trustworthy goods',
    26:  'Reliable and trustworthy goods',
    27:  'Stole a lot of R&D from a rival corporation',
    28:  'Stole a lot of R&D from a rival corporation',
    29:  'Stole a lot of R&D from a rival corporation',
    30:  'Stole a lot of R&D from a rival corporation',
    31:  'Stole a lot of R&D from a rival corporation',
    32:  'They have high-level political connections',
    33:  'They have high-level political connections',
    34:  'They have high-level political connections',
    35:  'They have high-level political connections',
    36:  'They have high-level political connections',
    37:  'They have high-level political connections',
    38:  'Rumored cover-up of a massive industrial accident',
    39:  'Rumored cover-up of a massive industrial accident',
    40:  'Rumored cover-up of a massive industrial accident',
    41:  'Rumored cover-up of a massive industrial accident',
    42:  'Rumored cover-up of a massive industrial accident',
    43:  'Rumored cover-up of a massive industrial accident',
    44:  'Stodgy and very conservative in their business plans',
    45:  'Stodgy and very conservative in their business plans',
    46:  'Stodgy and very conservative in their business plans',
    47:  'Stodgy and very conservative in their business plans',
    48:  'Stodgy and very conservative in their business plans',
    49:  'Stodgy and very conservative in their business plans',
    50:  '',
    51:  '',
    52:  '',
    53:  '',
    54:  'The company\'s owner is dangerously insane',
    55:  'The company\'s owner is dangerously insane',
    56:  'The company\'s owner is dangerously insane',
    57:  'The company\'s owner is dangerously insane',
    58:  'The company\'s owner is dangerously insane',
    59:  'The company\'s owner is dangerously insane',
    60:  'Rumored ties to a eugenics cult',
    61:  'Rumored ties to a eugenics cult',
    62:  'Rumored ties to a eugenics cult',
    63:  'Rumored ties to a eugenics cult',
    64:  'Rumored ties to a eugenics cult',
    65:  'Said to have a cache of pretech equipment',
    66:  'Said to have a cache of pretech equipment',
    67:  'Said to have a cache of pretech equipment',
    68:  'Said to have a cache of pretech equipment',
    69:  'Said to have a cache of pretech equipment',
    70:  'Said to have a cache of pretech equipment',
    71:  'Possibly teetering on the edge of bankruptcy',
    72:  'Possibly teetering on the edge of bankruptcy',
    73:  'Possibly teetering on the edge of bankruptcy',
    74:  'Possibly teetering on the edge of bankruptcy',
    75:  'Possibly teetering on the edge of bankruptcy',
    76:  'Possibly teetering on the edge of bankruptcy',
    77:  'Front for a planetary government\'s espionage arm',
    78:  'Front for a planetary government\'s espionage arm',
    79:  'Front for a planetary government\'s espionage arm',
    80:  'Front for a planetary government\'s espionage arm',
    81:  'Front for a planetary government\'s espionage arm',
    82:  'Secretly run by a psychic cabal',
    83:  'Secretly run by a psychic cabal',
    84:  'Secretly run by a psychic cabal',
    85:  'Secretly run by a psychic cabal',
    86:  'Secretly run by a psychic cabal',
    87:  'Secretly run by hostile aliens',
    88:  'Secretly run by hostile aliens',
    89:  'Secretly run by hostile aliens',
    90:  'Secretly run by hostile aliens',
    91:  'Secretly run by hostile aliens',
    92:  'Secretly run by an unbraked AI',
    93:  'Secretly run by an unbraked AI',
    94:  'Secretly run by an unbraked AI',
    95:  'Secretly run by an unbraked AI',
    96:  'They\'ve turned over a new leaf with the new CEO',
    97:  'They\'ve turned over a new leaf with the new CEO',
    98:  'They\'ve turned over a new leaf with the new CEO',
    99:  'Deeply entangled with the planetary underworld',
    100: 'Deeply entangled with the planetary underworld'
}

# Corporation class ------------------------------------------------------------
class Corporation(object):
    def __init__(self,
                 name         = '',
                 organization = '',
                 business     = '',
                 reputation   = ''):
        self.name         = name
        self.organization = organization
        self.business     = business